src/Entity/Transaction.php
<?php

namespace App\Entity;

use App\Repository\TransactionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TransactionRepository::class)]
class Transaction
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $bookingDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $valutaDate = null;

    #[ORM\Column]
    private ?int $amount = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $creditDebit = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $bookingText = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $descriptionRaw = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $bankCode = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $accountNumber = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\ManyToOne(inversedBy: 'transactions')]
    private ?Category $category = null;

    #[ORM\Column(length: 255)]
    private ?string $checksum = null;

    /**
     * @var Collection<int, SplitTransaction>
     */
    #[ORM\OneToMany(targetEntity: SplitTransaction::class, mappedBy: 'transaction', orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $splitTransactions;

    #[ORM\ManyToOne(inversedBy: 'transactions')]
    private ?SubAccount $subAccount = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?PayPalTransaction $payPalTransaction = null;

    public function __construct()
    {
        $this->splitTransactions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBookingDate(): ?\DateTimeInterface
    {
        return $this->bookingDate;
    }

    public function setBookingDate(\DateTimeInterface $bookingDate): static
    {
        $this->bookingDate = $bookingDate;

        return $this;
    }

    public function getValutaDate(): ?\DateTimeInterface
    {
        return $this->valutaDate;
    }

    public function setValutaDate(\DateTimeInterface $valutaDate): static
    {
        $this->valutaDate = $valutaDate;

        return $this;
    }

    public function getAmount(): ?int
    {
        return $this->amount;
    }

    public function getAmountAsCurrency(): ?float
    {
        return $this->amount / 100;
    }

    public function setAmount(int $amount): static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getAmountDifferenceAsCurrency(): ?float
    {
        if (!$this->hasSplitTransactions()) {
            return $this->getAmountAsCurrency();
        }

        $amount = $this->getAmount();
        foreach($this->getSplitTransactions() as $splitTransaction) {
            $amount -= $splitTransaction->getAmount();
        }

        return $amount / 100;
    }

    public function getCreditDebit(): ?string
    {
        return $this->creditDebit;
    }

    public function setCreditDebit(?string $creditDebit): static
    {
        $this->creditDebit = $creditDebit;

        return $this;
    }

    public function isCredit(): bool
    {
        return $this->getCreditDebit() === 'credit';
    }

    public function getBookingText(): ?string
    {
        return $this->bookingText;
    }

    public function setBookingText(?string $bookingText): static
    {
        $this->bookingText = $bookingText;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDescriptionRaw(): ?string
    {
        return $this->descriptionRaw;
    }

    public function setDescriptionRaw(?string $descriptionRaw): static
    {
        $this->descriptionRaw = $descriptionRaw;

        return $this;
    }

    public function getBankCode(): ?string
    {
        return $this->bankCode;
    }

    public function setBankCode(?string $bankCode): static
    {
        $this->bankCode = $bankCode;

        return $this;
    }

    public function getAccountNumber(): ?string
    {
        return $this->accountNumber;
    }

    public function setAccountNumber(?string $accountNumber): static
    {
        $this->accountNumber = $accountNumber;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getChecksum(): ?string
    {
        return $this->checksum;
    }

    public function setChecksum(string $checksum): static
    {
        $this->checksum = $checksum;

        return $this;
    }

    /**
     * @return Collection<int, SplitTransaction>
     */
    public function getSplitTransactions(): Collection
    {
        return $this->splitTransactions;
    }

    public function addSplitTransaction(SplitTransaction $splitTransaction): static
    {
        if (!$this->splitTransactions->contains($splitTransaction)) {
            $this->splitTransactions->add($splitTransaction);
            $splitTransaction->setTransaction($this);
        }

        return $this;
    }

    public function removeSplitTransaction(SplitTransaction $splitTransaction): static
    {
        if ($this->splitTransactions->removeElement($splitTransaction)) {
            // set the owning side to null (unless already changed)
            if ($splitTransaction->getTransaction() === $this) {
                $splitTransaction->setTransaction(null);
            }
        }

        return $this;
    }

    public function hasSplitTransactions(): bool
    {
        return count($this->splitTransactions) > 0;
    }

    public function getSubAccount(): ?SubAccount
    {
        return $this->subAccount;
    }

    public function setSubAccount(?SubAccount $subAccount): static
    {
        $this->subAccount = $subAccount;

        return $this;
    }

    public function getPayPalTransaction(): ?PayPalTransaction
    {
        return $this->payPalTransaction;
    }

    public function setPayPalTransaction(?PayPalTransaction $payPalTransaction): static
    {
        $this->payPalTransaction = $payPalTransaction;

        return $this;
    }
}

src/Controller/GridController.php
<?php

namespace App\Controller;

use App\Repository\CategoryGroupRepository;
use App\Repository\CategoryRepository;
use App\Repository\SplitTransactionRepository;
use App\Repository\TransactionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\MapQueryParameter;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\UX\Turbo\TurboBundle;

class GridController extends AbstractController
{
    #[Route('/grid/monthly', name: 'app_grid_monthly', methods: ['GET'])]
    public function index(
        TransactionRepository $repository,
        CategoryGroupRepository $groupRepository,
        #[MapQueryParameter] int $month = null,
        #[MapQueryParameter] int $year = null,
        #[MapQueryParameter] string $sort = 'valutaDate',
        #[MapQueryParameter] string $sortDirection = 'ASC',
        #[MapQueryParameter] string $query = null,
    ): Response
    {
        if (null === $month) {
            $month = date('m');
        }

        if (null === $year) {
            $year = date('Y');
        }

        $validSorts = ['valutaDate', 'category'];
        $sort = in_array($sort, $validSorts) ? $sort : 'valutaDate';

        return $this->render('grid/list.html.twig', [
            'transactions' => $repository->findBySearch($month, $year, $sort, $sortDirection, $query),
            'month' => $month,
            'year' => $year,
            'sort' => $sort,
            'sortDirection' => $sortDirection,
            'categoryGroups' => $groupRepository->findBy([], ['name' => 'ASC']),
            'query' => $query
        ]);
    }

    #[Route('/grid/transaction/set-category', name: 'app_grid_transaction_set_category', methods: ['POST'])]
    public function editCategory(TransactionRepository $transactionRepository, SplitTransactionRepository $splitTransactionRepository, EntityManagerInterface $entityManager, CategoryRepository $categoryRepository, Request $request): Response
    {
        $transaction = $transactionRepository->findOneById($request->request->getInt('transactionId'));
        $catgory = $categoryRepository->findOneById($request->request->getInt('categoryId'));

        $request->setRequestFormat(TurboBundle::STREAM_FORMAT);

        if ($request->request->has('splitTransactionId') && 0 !== $request->request->get('splitTransactionId')) {
            $splitTransaction = $splitTransactionRepository->findOneById($request->request->getInt('splitTransactionId'));

            $splitTransaction->setCategory($catgory);
            $entityManager->persist($transaction);
            $entityManager->flush();

            $this->addFlash('success', 'Transaction updated!');

            return $this->render('grid/row.stream.html.twig', [
                'transaction' => $transaction,
                'splitTransaction' => $splitTransaction,
            ]);
        } else {
            $transaction->setCategory($catgory);
            $entityManager->persist($transaction);
            $entityManager->flush();

            $this->addFlash('success', 'Transaction updated!');

            return $this->render('grid/row.stream.html.twig', [
                'transaction' => $transaction,
            ]);
        }
    }
}

templates/grid/_categoryDropdown.html.twig
<div
    data-grid-target="dropdown"
    class="z-10 absolute hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700"
>
    <form
        action="{{ path('app_grid_transaction_set_category') }}"
        method="POST"
        data-grid-target="dropdownForm"
    >
        <input data-grid-target="dropdownTransactionValue" type="hidden" name="transactionId" value="" />
        <input data-grid-target="dropdownSplitTransactionValue" type="hidden" name="splitTransactionId" value="" />
        <select
            class="bg-gray-50 border border-gray-300 text-gray-900 text-xs rounded focus:ring-blue-500 focus:border-blue-500 block w-full p-1 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            name="categoryId"
            data-action="change->grid#submit"
            data-grid-target="dropdownSelect"
        >
            <option value="">Please choose</option>
            {% for group in categoryGroups %}
                <optgroup label="{{ group.name }}">
                    {% for category in group.categories %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </optgroup>
            {% endfor %}
        </select>
    </form>
</div>

templates/grid/_row.html.twig
<td class="p-1 px-2 text-xs font-normal text-gray-600 whitespace-nowrap dark:text-gray-400">
    {% if splitTransaction is defined %}{% endif%}
</td>
<td class="p-1 px-2 text-xs font-normal text-gray-600 whitespace-nowrap dark:text-gray-400">
    {{ transaction.valutaDate|date('d.m.Y') }}
</td>
<td class="p-1 px-2 text-xs font-normal text-gray-600 whitespace-nowrap dark:text-gray-400">
    {% if splitTransaction is defined %}
        {% set popOverId = splitTransaction.id %}
    {% else %}
        {% set popOverId = transaction.id %}
    {% endif%}
    <span data-popover-target="popover-transaction-{{ popOverId }}">{{ transaction.name }}</span>

    <div
        data-popover id="popover-transaction-{{ popOverId }}"
        role="tooltip"
        class="absolute z-30 invisible inline-block text-xs text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-80 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400"
    >
        <div class="px-3 py-2 text-wrap text-ellipsis overflow-hidden ...">
            <p>{{ transaction.descriptionRaw|replace({'/': ' ', '+' : ' '}) }}</p>
        </div>
        <div data-popper-arrow></div>
    </div>
</td>
<td
    class="p-1 px-2 text-xs font-normal text-gray-600 whitespace-nowrap dark:text-gray-400"
    data-action="click->grid#showDropdown"
    data-transaction-id="{{ transaction.id }}"
    data-split-transaction-id="{% if splitTransaction is defined %}{{ splitTransaction.id }}{% else %}0{% endif %}"
    data-transaction-category-id="{% if splitTransaction is defined and splitTransaction.category %}{{ splitTransaction.category.id }}{% elseif transaction.category %}{{ transaction.category.id }}{% endif %}"
>
    {% if splitTransaction is defined %}
        {{ splitTransaction.category.name }}
    {% elseif transaction.category %}
        {{ transaction.category.name }}
    {% endif %}
</td>
<td class="p-1 px-2 pe-4 text-xs font-normal text-right text-gray-600 whitespace-nowrap dark:text-gray-400">
    {% if transaction.isCredit %}
        {% set fontClass = 'text-green-500' %}
    {% else %}
        {% set fontClass = 'text-red-600' %}
    {% endif %}

    {% if splitTransaction is defined %}
        <span class="font-semibold {{ fontClass }}">{{ splitTransaction.amountAsCurrency|format_currency('EUR', {}) }}</span>
    {% else %}
        <span class="font-semibold {{ fontClass }}">{{ transaction.amountAsCurrency|format_currency('EUR', {}) }}</span>
    {% endif %}
</td>

templates/grid/list.html.twig
{% extends 'base.html.twig' %}

{% macro sortArrow(sortName, sort, sortDirection) %}
    {% if sort == sortName %}
        {% if sortDirection == 'asc' %}
            <svg xmlns="http://www.w3.org/2000/svg" class="inline-block w-4 h-4" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <path d="M6 15l6 -6l6 6"></path>
            </svg>
        {% else %}
            <svg xmlns="http://www.w3.org/2000/svg" class="inline-block w-4 h-4" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <path d="M6 9l6 6l6 -6"></path>
            </svg>
        {% endif %}
    {% else %}
        <!-- up and down arrow svg -->
        <svg xmlns="http://www.w3.org/2000/svg" class="inline-block w-4 h-4 text-slate-300" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <path d="M8 9l4 -4l4 4"></path>
            <path d="M16 15l-4 4l-4 -4"></path>
        </svg>
    {% endif %}
{% endmacro %}

{% block header %}
    {% include '_header.html.twig' %}
{% endblock %}

{% block body %}
<twig:MonthPicker></twig:MonthPicker>

<turbo-frame
    id="transaction-list"
    class="aria-busy:opacity-50 aria-busy:blur-sm transition-all"
    data-controller="grid"
    data-action="click@window->grid#hide"
>
    <table class="min-w-full divide-y divide-gray-200 table-fixed dark:divide-gray-600">
    <thead>
    <tr>
        <th scope="col" class="sticky top-16 p-2 text-xs font-medium text-left text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-700"></th>
        <th scope="col" class="sticky top-16 p-2 text-xs font-medium text-left text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-700">
            <a href="{{ path('app_grid_monthly', {
                ...app.request.query.all(),
                sort: 'valutaDate',
                sortDirection: sort == 'valutaDate' and sortDirection == 'asc' ? 'desc' : 'asc',
            }) }}">
                Valuta date {{ _self.sortArrow('valutaDate', sort, sortDirection) }}
            </a>
        </th>
        <th scope="col" class="sticky top-16 p-2 text-xs font-medium text-left text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-700">Recipient</th>
        <th scope="col" class="sticky top-16 p-2 text-xs font-medium text-left text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-700">
            <a href="{{ path('app_grid_monthly', {
                ...app.request.query.all(),
                sort: 'category',
                sortDirection: sort == 'category' and sortDirection == 'asc' ? 'desc' : 'asc',
            }) }}">
                Category {{ _self.sortArrow('category', sort, sortDirection) }}
            </a>
        </th>
        <th scope="col" class="sticky top-16 p-2 pe-4 text-xs font-medium text-right text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-700">Amount</th>
    </tr>
    </thead>
    <tbody class="bg-white divide-y divide-gray-200 dark:bg-gray-800 dark:divide-gray-700">
    {% for transaction in transactions %}
        {% if transaction.hasSplitTransactions %}

            {% for splitTransaction in transaction.splitTransactions %}
                <tr
                    class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700 hover:bg-yellow-100 dark:hover:bg-gray-600"
                    id="split-transaction-list-item-{{ splitTransaction.id }}"
                >
                    {% include 'grid/_row.html.twig' with { 'transaction': transaction, 'splitTransaction': splitTransaction } %}
                </tr>
            {% endfor %}

        {% else %}
            <tr
                class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700 hover:bg-yellow-100 dark:hover:bg-gray-600"
                id="transaction-list-item-{{ transaction.id }}"
            >
                {% include 'grid/_row.html.twig' with { 'transaction': transaction } %}
            </tr>
        {% endif %}
    {% else %}
        <tr>
            <td colspan="5" class="p-4 text-xs font-medium text-left text-gray-500 uppercase dark:text-gray-400">No records found</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

    {% include 'grid/_categoryDropdown.html.twig' %}
</turbo-frame>
{% endblock %}

templates/grid/monthly.html.twig
{% extends 'base.html.twig' %}

{% macro sortArrow(sortName, sort, sortDirection) %}
    {% if sort == sortName %}
        {% if sortDirection == 'asc' %}
            <svg xmlns="http://www.w3.org/2000/svg" class="inline-block w-4 h-4" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <path d="M6 15l6 -6l6 6"></path>
            </svg>
        {% else %}
            <svg xmlns="http://www.w3.org/2000/svg" class="inline-block w-4 h-4" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <path d="M6 9l6 6l6 -6"></path>
            </svg>
        {% endif %}
    {% else %}
        <!-- up and down arrow svg -->
        <svg xmlns="http://www.w3.org/2000/svg" class="inline-block w-4 h-4 text-slate-300" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <path d="M8 9l4 -4l4 4"></path>
            <path d="M16 15l-4 4l-4 -4"></path>
        </svg>
    {% endif %}
{% endmacro %}

{% block body %}
<twig:MonthPicker></twig:MonthPicker>

<turbo-frame id="transaction-list" class="aria-busy:opacity-50 aria-busy:blur-sm transition-all">
<table class="min-w-full divide-y divide-gray-200 table-fixed dark:divide-gray-600">
    <thead>
    <tr>
        <th scope="col" class="sticky top-16 p-2 text-xs font-medium text-left text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-700"></th>
        <th scope="col" class="sticky top-16 p-2 text-xs font-medium text-left text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-700">
            <a href="{{ path('app_grid_monthly', {
                ...app.request.query.all(),
                sort: 'valutaDate',
                sortDirection: sort == 'valutaDate' and sortDirection == 'asc' ? 'desc' : 'asc',
            }) }}">
                Valuta date {{ _self.sortArrow('valutaDate', sort, sortDirection) }}
            </a>
        </th>
        <th scope="col" class="sticky top-16 p-2 text-xs font-medium text-left text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-700">Recipient</th>
        <th scope="col" class="sticky top-16 p-2 text-xs font-medium text-left text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-700">
            <a href="{{ path('app_grid_monthly', {
                ...app.request.query.all(),
                sort: 'category',
                sortDirection: sort == 'category' and sortDirection == 'asc' ? 'desc' : 'asc',
            }) }}">
                Category {{ _self.sortArrow('category', sort, sortDirection) }}
            </a>
        </th>
        <th scope="col" class="sticky top-16 p-2 text-xs font-medium text-right text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-700">Amount</th>
    </tr>
    </thead>
    <tbody class="bg-white divide-y divide-gray-200 dark:bg-gray-800 dark:divide-gray-700">
    {% for transaction in transactions %}
        <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700 hover:bg-yellow-100 dark:hover:bg-gray-600">
            <td class="p-1 px-2 text-xs font-normal text-gray-600 whitespace-nowrap dark:text-gray-400"></td>
            <td class="p-1 px-2 text-xs font-normal text-gray-600 whitespace-nowrap dark:text-gray-400">{{ transaction.valutaDate|date('d.m.Y') }}</td>
            <td class="p-1 px-2 text-xs font-normal text-gray-600 whitespace-nowrap dark:text-gray-400">{{ transaction.name }}</td>
            <td class="p-1 px-2 text-xs font-normal text-gray-600 whitespace-nowrap dark:text-gray-400">{% if transaction.category %}{{ transaction.category.name }}{% endif %}</td>
            <td class="p-1 px-2 text-xs font-normal text-right text-gray-600 whitespace-nowrap dark:text-gray-400">
                <span class="font-semibold {% if transaction.isCredit %}text-green-500{% else %}text-red-600{% endif %}">
                {{ transaction.amount }}
                </span>
            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="5" class="p-4 text-xs font-medium text-left text-gray-500 uppercase dark:text-gray-400">No records found</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/grid/row.stream.html.twig
{% if splitTransaction is defined %}
    {% set target = "split-transaction-list-item-" ~ splitTransaction.id  %}
{% else %}
    {% set target = "transaction-list-item-" ~ transaction.id  %}
{% endif %}
<turbo-stream action="update" target="{{ target }}">
    <template>
        {% if splitTransaction is defined %}
            {% include 'grid/_row.html.twig' with { 'transaction': transaction, 'splitTransaction': splitTransaction } %}
        {% else %}
            {% include 'grid/_row.html.twig' with { 'transaction': transaction } %}
        {% endif %}
    </template>
</turbo-stream>

{% include '_flashes.html.twig' %}