src/Entity/CategoryAssignmentRule.php
<?php

namespace App\Entity;

use App\Repository\CategoryAssignmentRuleRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CategoryAssignmentRuleRepository::class)]
class CategoryAssignmentRule
{
    const TYPE_SIMPLE = 0;
    const TYPE_REGEX = 1;
    const AVAILABLE_TYPES = [
        self::TYPE_SIMPLE => 'Simple',
        self::TYPE_REGEX => 'Regex',
    ];
    const AVAILABLE_TYPE_CHOICES = [
        'Simple' => self::TYPE_SIMPLE,
        'Regex' => self::TYPE_REGEX,
    ];

    const TRANSACTION_FIELD_NAME = 0;
    const TRANSACTION_FIELD_DESCRIPTION = 1;
    const AVAILABLE_TRANSACTION_FIELDS = [
        self::TRANSACTION_FIELD_NAME => 'Name',
        self::TRANSACTION_FIELD_DESCRIPTION => 'Description',
    ];
    const AVAILABLE_TRANSACTION_FIELD_CHOICE = [
        'Name' => self::TRANSACTION_FIELD_NAME,
        'Description' => self::TRANSACTION_FIELD_DESCRIPTION,
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $rule = null;

    #[ORM\Column]
    #[Assert\NotBlank]
    private ?int $type = null;

    #[ORM\Column]
    #[Assert\NotBlank]
    private ?int $transactionField = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank]
    private ?Category $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function getTypeName(): string
    {
        return self::AVAILABLE_TYPES[$this->type] ?? 'not defined';
    }

    public function setType(int $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getTransactionField(): ?int
    {
        return $this->transactionField;
    }

    public function getTransactionFieldName(): string
    {
        return self::AVAILABLE_TRANSACTION_FIELDS[$this->transactionField] ?? 'not defined';
    }

    public function setTransactionField(int $transactionField): static
    {
        $this->transactionField = $transactionField;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getRule(): ?string
    {
        return $this->rule;
    }

    public function setRule(string $rule): static
    {
        $this->rule = $rule;

        return $this;
    }
}

src/Controller/SettingsRuleController.php
<?php

namespace App\Controller;

use App\Entity\CategoryAssignmentRule;
use App\Form\CategoryAssignmentRuleType;
use App\Repository\CategoryAssignmentRuleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/settings/rules')]
class SettingsRuleController extends AbstractController
{
    #[Route('/', name: 'app_settings_rule_index', methods: ['GET'])]
    public function index(CategoryAssignmentRuleRepository $repository): Response
    {
        return $this->render('settings_rule/index.html.twig', [
            'rules' => $repository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_settings_rule_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $rule = new CategoryAssignmentRule();
        $form = $this->createForm(CategoryAssignmentRuleType::class, $rule, [
            'action' => $this->generateUrl('app_settings_rule_new'),
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($rule);
            $entityManager->flush();

            $this->addFlash('success', 'Assignment Rule created');

            return $this->redirectToRoute('app_settings_rule_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('settings_rule/new.html.twig', [
            'rule' => $rule,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_settings_rule_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, CategoryAssignmentRule $rule, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CategoryAssignmentRuleType::class, $rule, [
            'action' => $this->generateUrl('app_settings_rule_edit', ['id' => $rule->getId()]),
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            $this->addFlash('success', 'Assignment Rule updated');

            return $this->redirectToRoute('app_settings_rule_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('settings_rule/edit.html.twig', [
            'rule' => $rule,
            'form' => $form,
        ]);
    }
}

templates/settings_rule/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}

    {% if app.request.headers.get('turbo-frame') is not empty %}
        <div class="bottom-0 left-0 flex justify-start w-full pb-4 space-x-4 md:px-4 md:absolute">
            <button class="text-white bg-green-700 hover:bg-green-800 focus:outline-none font-medium rounded-lg text-sm px-5 py-2 text-center mt-4 inline-flex items-center">
                <i class="fa-solid fa-floppy-disk me-2.5"></i>{{ button_label|default('Save') }}
            </button>
        </div>
    {% else %}
        <div class="d-flex justify-content-end">
            <button class="text-white bg-green-700 hover:bg-green-800 focus:outline-none font-medium rounded-lg text-sm px-5 py-2 text-center mt-4 inline-flex items-center">
                <i class="fa-solid fa-floppy-disk me-2.5"></i>{{ button_label|default('Save') }}
            </button>
        </div>
    {% endif %}
{{ form_end(form) }}

templates/settings_rule/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <twig:Header title=""></twig:Header>

    <div class="grid grid-cols-6 gap-4 px-4 pt-6 dark:bg-gray-900">
        <twig:Card title="Edit Category Assignment Rule" grid="col-start-2 col-end-5">
            <turbo-frame id="form-drawer">

                {% if app.request.headers.get('turbo-frame') is not empty %}
                    <h5 id="drawer-right-label" class="inline-flex items-center mb-4 text-base font-semibold text-gray-500 dark:text-gray-400">
                        <i class="fa-solid fa-tag me-2.5"></i>Edit Category Assignment Rule
                    </h5>
                {% endif %}

                {{ include('settings_rule/_form.html.twig') }}
            </turbo-frame>
        </twig:Card>
    </div>
{% endblock %}

templates/settings_rule/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <twig:Header title="Category Assignment Rules">
        <div class="sm:flex">
            <div class="flex items-center ml-auto space-x-2 sm:space-x-3">
                <a
                    class="px-3 py-2 text-xs font-medium text-center inline-flex items-center text-white bg-[#112D4E] rounded-lg hover:bg-[#112D4E]/90 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                    data-turbo-frame="form-drawer"
                    href="{{ path('app_settings_rule_new') }}"
                >
                    <svg class="w-3 h-3 text-white me-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                        <path fill-rule="evenodd" d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12Zm11-4.243a1 1 0 1 0-2 0V11H7.757a1 1 0 1 0 0 2H11v3.243a1 1 0 1 0 2 0V13h3.243a1 1 0 1 0 0-2H13V7.757Z" clip-rule="evenodd"/>
                    </svg>
                    Add Rule
                </a>
            </div>
        </div>
    </twig:Header>

    <twig:Content>
        <table class="min-w-full divide-y divide-gray-200 table-fixed dark:divide-gray-600">
            <thead class="bg-gray-100 dark:bg-gray-700">
            <tr>
                <th scope="col" class="p-3 text-xs font-medium text-left text-gray-500 uppercase dark:text-gray-400">Rule</th>
                <th scope="col" class="p-3 text-xs font-medium text-left text-gray-500 uppercase dark:text-gray-400">Type</th>
                <th scope="col" class="p-3 text-xs font-medium text-left text-gray-500 uppercase dark:text-gray-400">Transaction Field</th>
                <th scope="col" class="p-3 text-xs font-medium text-left text-gray-500 uppercase dark:text-gray-400">Category</th>
                <th scope="col" class="p-3 text-xs font-medium text-center text-gray-500 uppercase dark:text-gray-400">Actions</th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200 dark:bg-gray-800 dark:divide-gray-700">
            {% for rule in rules %}
                <tr class="hover:bg-gray-100 dark:hover:bg-gray-700">
                    <td class="p-3 text-sm font-normal text-gray-500 whitespace-nowrap dark:text-gray-400">{{ rule.rule }}</td>
                    <td class="p-3 text-sm font-normal text-gray-500 whitespace-nowrap dark:text-gray-400">{{ rule.typeName }}</td>
                    <td class="p-3 text-sm font-normal text-gray-500 whitespace-nowrap dark:text-gray-400">{{ rule.transactionFieldName }}</td>
                    <td class="p-3 text-sm font-normal text-gray-500 whitespace-nowrap dark:text-gray-400">{{ rule.category.name }}</td>
                    <td class="p-3 space-x-2 text-gray-500 whitespace-nowrap text-center">
                        <a
                            href="{{ path('app_settings_rule_edit', {'id': rule.id}) }}"
                            data-turbo-frame="form-drawer"
                        >
                            <i class="fa-solid fa-square-pen text-lg hover:text-gray-900"></i>
                        </a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5" class="p-4 text-xs font-medium text-left text-gray-500 uppercase dark:text-gray-400">No records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </twig:Content>
{% endblock %}

templates/settings_rule/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <twig:Header title=""></twig:Header>

    <div class="grid grid-cols-6 gap-4 px-4 pt-6 dark:bg-gray-900">
        <twig:Card title="Add Category Assignment Rule" grid="col-start-2 col-end-5">
            <turbo-frame id="form-drawer">

                {% if app.request.headers.get('turbo-frame') is not empty %}
                    <h5 id="drawer-right-label" class="inline-flex items-center mb-4 text-base font-semibold text-gray-500 dark:text-gray-400">
                        <i class="fa-solid fa-tag me-2.5"></i>Add Category Assignment Rule
                    </h5>
                {% endif %}

                {{ include('settings_rule/_form.html.twig') }}
            </turbo-frame>
        </twig:Card>
    </div>
{% endblock %}